/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Enrique
 */
public class Shilebuf extends javax.swing.JFrame {

    /**
     * Creates new form Shilebuf
     */
    public Shilebuf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenuBar();
        motivationMenu = new javax.swing.JMenu();
        LAmenu = new javax.swing.JMenuItem();
        memeMenu = new javax.swing.JMenuItem();
        catMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        motivationMenu.setText("Motivation");

        LAmenu.setText("Shia LaBeouf");
        LAmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAmenuActionPerformed(evt);
            }
        });
        motivationMenu.add(LAmenu);

        memeMenu.setText("Memes");
        memeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memeMenuActionPerformed(evt);
            }
        });
        motivationMenu.add(memeMenu);

        catMenu.setText("RandomCatVideo");
        catMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catMenuActionPerformed(evt);
            }
        });
        motivationMenu.add(catMenu);

        menu.add(motivationMenu);

        jMenu1.setText("About");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        menu.add(jMenu1);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catMenuActionPerformed
        // TODO add your handling code here:Desktop d = Desktop.getDesktop();
        Desktop d = Desktop.getDesktop();
        try {
            d.browse(new URI("https://procatinator.com/"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Shilebuf.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Shilebuf.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_catMenuActionPerformed

    private void LAmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAmenuActionPerformed
        // TODO add your handling code here:
        Desktop d = Desktop.getDesktop();
        try {
            d.browse(new URI("https://www.youtube.com/watch?v=ZXsQAXx_ao0"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Shilebuf.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Shilebuf.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_LAmenuActionPerformed

    private void memeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memeMenuActionPerformed
        // TODO add your handling code here:
            Desktop d = Desktop.getDesktop();
        try {
            d.browse(new URI("https://www.reddit.com/r/meme/"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(Shilebuf.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Shilebuf.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_memeMenuActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        About ab = new About();
        ab.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shilebuf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shilebuf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shilebuf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shilebuf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shilebuf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LAmenu;
    private javax.swing.JMenuItem catMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem memeMenu;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu motivationMenu;
    // End of variables declaration//GEN-END:variables
}
